# Project Settings
nav:
  - Home: 'index.md'
  - About Us:
    - Board Members: 'about-us/board-members.md'
    - Meeting Info: 'about-us/meeting-info.md'
  - By-Laws:
    - Preamble: 'by-laws/preamble.md'
    - I. Name: 'by-laws/name.md'
    - II. Affiliation: 'by-laws/affiliation.md'
    - III. Doctrinal Standards: 'by-laws/doctrinal_standards.md'
    - IV. Purpose: 'by-laws/purpose.md'
    - V. Definitions: 'by-laws/definitions.md'
    - VI. Association Membership: 'by-laws/association_membership.md'
    - VII. Association Funding: 'by-laws/association_funding.md'
    - VIII. Delegate Assembly: 'by-laws/delegate_assembly.md'
    - IX. Board of Directors: 'by-laws/board_of_directors.md'
    - X. Officers: 'by-laws/officers.md'
    - XI. Committees: 'by-laws/committees.md'
    - XII. Miscellaneous Provisions: 'by-laws/miscellaneous_provisions.md'
    - XIII. Ammendment: 'by-laws/ammendment.md'
    - XIV. Dissolution: 'by-laws/dissolution.md'
  - Board Policy:
    - Board of Directors:
      - Board of Directors: 'board-policy/board-of-directors/index.md'
    - Responsibilities:
      - Powers: 'board-policy/responsibilities-of-directors/powers-of-board.md'
      - Responsibilities: 'board-policy/responsibilities-of-directors/responsibilities-of-board.md'
      - Duties: 'board-policy/responsibilities-of-directors/duties-of-board.md'
    - Elections:
      - Qualifications: 'board-policy/election-of-directors/qualifications-of-directors.md'
      - Election: 'board-policy/election-of-directors/election-of-directors.md'
      - Vacancies: 'board-policy/election-of-directors/vacancies.md'
    - Officer Duties:
      - Chairperson: 'board-policy/officers-of-board/chairperson.md'
      - Vice Chairperson: 'board-policy/officers-of-board/vice-chairperson.md'
      - Secretary: 'board-policy/officers-of-board/secretary.md'
      - Treasurer:  'board-policy/officers-of-board/treasurer.md'
      - Consultant: 'board-policy/officers-of-board/consultant.md'
      - Chaplain: 'board-policy/officers-of-board/chaplain.md'
    - Committees:
      - Standing:
        - Standing: 'board-policy/committees-of-board/standing-committee/index.md'
        - Student Recruitment: 'board-policy/committees-of-board/standing-committee/student-recruitment-committee.md'
      - Ad Hoc:
        - Ad Hoc: 'board-policy/committees-of-board/ad-hoc-committee/index.md'
        - Staffing: 'board-policy/committees-of-board/ad-hoc-committee/ad-hoc-staffing-committee.md'
        - Building: 'board-policy/committees-of-board/ad-hoc-committee/ad-hoc-building-committee.md'
        - Student Recruitment: 'board-policy/committees-of-board/ad-hoc-committee/ad-hoc-student-recruitment-committee.md'
        - Merit: 'board-policy/committees-of-board/ad-hoc-committee/ad-hoc-merit-scholorship-committee.md'
    - Policy:
      - Development: 'board-policy/policy/development.md'
      - Adoption: 'board-policy/policy/adoption.md'
      - Review:
        - Review: 'board-policy/policy/review-and-revision/index.md'
        - Plan for Revision: 'board-policy/policy/review-and-revision/plan-for-revision.md'
      - Dissemination: 'board-policy/policy/dissemination.md'
      - Suspension: 'board-policy/policy/suspension.md'
      - In Absence: 'board-policy/policy/in-absence.md'
    - Board Meetings:
      - Regular Meetings: 'board-policy/board-meetings/regular-meeting.md'
      - Special Meetings: 'board-policy/board-meetings/special-meeting.md'
      - Work Sessions: 'board-policy/board-meetings/work-sessions.md'
      - Meeting Notice: 'board-policy/board-meetings/meeting-notice.md'
      - Quorum: 'board-policy/board-meetings/quorum.md'
      - Rules of Order: 'board-policy/board-meetings/rules-of-order.md'
      - Meeting Agenda: 'board-policy/board-meetings/meeting-agenda.md'
      - Open Meetings: 'board-policy/board-meetings/open-meetings.md'
      - Closed Sessions: 'board-policy/board-meetings/closed-sessions.md'
    - Association Participation:
      - Association Participation: 'board-policy/association-member-participation/index.md'
      - General Complaints: 'board-policy/association-member-participation/general-complaints.md'
      - Whistle Blower: 'board-policy/association-member-participation/whistle-blower.md'
    - Public Hearings:
      - Public Hearings: 'board-policy/public-hearings/index.md'
    - Board Records:
      - Board Records: 'board-policy/board-records/index.md'
      - Board Minutes: 'board-policy/board-records/board-minutes.md'
    - Retention Policy:
      - Retention Policy: 'board-policy/retention-policy/index.md'
    - Gifts to Directors:
      - Gifts to Directors: 'board-policy/gifts-to-directors/index.md'
  - Onboarding:
    - Checklist: 'onboarding/checklist.md'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike

# Site settings - effect what is shown on pages throughout the project
site_name: VLS Board of Directors
copyright: Copyright &copy; 2022 - 2023


# Site look and feel
theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: 'deep purple'
      accent: 'deep purple'

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: images/valley_logo_small.png

  features:
    - navigation.instant    # Enables instant loading
    - navigation.tracking   # Address bar URL automatically updated with active anchor highlighted in table of contents
    # - navigation.tabs       # Renders top-level sections in menu layer below header
    - navigation.top        # Show back-to-top button
    # - navigation.expand     # Expands all colapsible sections in left sidebar
    # - navigation.sections
    - navigation.indexes
    - navigation.footer
