# Project Settings
site_name: VLS Board of Directors
copyright: Copyright © 2022-2023 Valley Lutheran School. All Rights Reserved.

# Site settings - effect what is shown on pages throughout the project
extra:
  generator: false  # Toggles off "Made with Material for MkDocs"
extra_css:
  - stylesheets/extra.css

# Site look and feel
theme:
  name: material
  # custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: 'deep purple'
      accent: 'deep purple'

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: images/valley_logo_small.png

  features:
    - navigation.instant    # Enables instant loading
    - navigation.tracking   # Address bar URL automatically updated with active anchor highlighted in table of contents
    - navigation.tabs       # Renders top-level sections in menu layer below header
    - navigation.top        # Show back-to-top button
    - navigation.expand     # Expands all collapsible sections in left sidebar
    - navigation.sections
    - navigation.indexes
    #- navigation.footer
    - navigation.prune
    - navigation.tabs.sticky
    - toc.follow

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

plugins:
  - awesome-pages
  - glightbox
  - git-revision-date-localized:
      enable_creation_date: false
  - search
  - autorefs