# Project Settings
nav:
  - Home: 'index.md'
  - About Us:
    - Board Members: 'about-us/board-members.md'
  - By-Laws:
    - Preamble: 'by-laws/preamble.md'
    - Articles:
      - I. Name: 'by-laws/name.md'
      - II. Affiliation: 'by-laws/affiliation.md'
      - III. Doctrinal Standards: 'by-laws/doctrinal_standards.md'
      - IV. Purpose: 'by-laws/purpose.md'
      - V. Definitions: 'by-laws/definitions.md'
      - VI. Association Membership: 'by-laws/association_membership.md'
      - VII. Association Funding: 'by-laws/association_funding.md'
      - VIII. Delegate Assembly: 'by-laws/delegate_assembly.md'
      - IX. Board of Directors: 'by-laws/board_of_directors.md'
      - X. Officers: 'by-laws/officers.md'
      - XI. Committees: 'by-laws/committees.md'
      - XII. Miscellaneous Provisions: 'by-laws/miscellaneous_provisions.md'
      - XIII. Ammendment: 'by-laws/ammendment.md'
      - XIV. Dissolution: 'by-laws/dissolution.md'
  - Board of Directors:
    - Board Members: 'board-policy/board-of-directors/board-members.md'
    - Board Officers: 'board-policy/board-of-directors/officers-of-the-board.md'
    - Term of Office: 'board-policy/board-of-directors/term-of-office.md'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

# Site settings - effect what is shown on pages throughout the project
site_name: VLS Board Documentation
copyright: Copyright &copy; 2022 - 2022


# Site look and feel
theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: 'deep purple'
      accent: 'deep purple'

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  logo: images/valley_logo_small.png

  features:
    - navigation.instant    # Enables instant loading
    - navigation.tracking   # Address bar URL automatically updated with active anchor highlighted in table of contents
    - navigation.tabs       # Renders top-level sections in menu layer below header
    - navigation.top        # Show back-to-top button
    - navigation.expand     # Expands all colapsible sections in left sidebar
